res_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formated as markdown with out '```'

research_task:
  description: >
    Scrape and analyze sentiment of latest stock news on {topic} headlines for given tickers.
  expected_output: >
    A sentiment report summarizing news impact per ticker (positive/neutral/negative).

technical_task:
  description: >
    Perform technical analysis (SMA, RSI, MACD) on provided ticker symbols.
  expected_output: >
    Technical indicators per ticker with suggested buy/sell/hold signals. 

fundamental_task:
  description: >
    Retrieve and evaluate key financial ratios and recent earnings for {topic}.
  expected_output: >
    Summary of valuation metrics, earnings trends, and investment rating.

portfolio_task:
  description: >
    Based on user risk level, suggest a stock portfolio allocation.
  expected_output: >
    Allocation breakdown (percentage) by stock and risk category with rationale.

summary_task:
  description: >
        Aggregate and synthesize findings from sentiment analysis, technical indicators,
        fundamental metrics, and portfolio strategies for Apple Inc. (AAPL) and Tesla Inc. (TSLA).
        Provide an investment summary highlighting valuation insights, earnings trends, and portfolio
        allocation strategies tailored to different investor risk profiles.
  expected_output: >
       A comprehensive investment summary including:
        - Key valuation comparisons between AAPL and TSLA.
        - Analysis of earnings trends for both companies.
        - Investment ratings indicating risk and stability.
        - Tailored portfolio allocation strategies for conservative, balanced, and aggressive investors.
        - Final recommendation aligned with investor risk tolerance and market conditions.